// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCp9qC3kd3szOiU-imBMi1cpBe5i4yLU',
    appId: '1:892746446757:web:47f593542bfb5f92c65a4c',
    messagingSenderId: '892746446757',
    projectId: 'hj213-my-photo',
    authDomain: 'hj213-my-photo.firebaseapp.com',
    storageBucket: 'hj213-my-photo.appspot.com',
    measurementId: 'G-2H033DX7LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHIKNuQkwmZaQduCthg8oP7NCIb939Fk',
    appId: '1:892746446757:android:931dd664a487c9e3c65a4c',
    messagingSenderId: '892746446757',
    projectId: 'hj213-my-photo',
    storageBucket: 'hj213-my-photo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn07_wxzTqaKXn9BaB_OzyDIJZypQJJRg',
    appId: '1:892746446757:ios:7ef3997907197a64c65a4c',
    messagingSenderId: '892746446757',
    projectId: 'hj213-my-photo',
    storageBucket: 'hj213-my-photo.appspot.com',
    iosClientId: '892746446757-5o9alc47usdldrkts0r79bsu115c7d81.apps.googleusercontent.com',
    iosBundleId: 'edu.skku.sco.hj213.myPhoto',
  );
}
